### ISSUE TITLE
Update readme to indicate this package no longer works!!!

### ISSUE THREAD

**Issue by jslingsby** [vt-arc/wosr#14]
And perhaps remove from CRAN too?

It's a bit rude to have it out there, but then one can only find out it no linger works by reading issue strings? I'm sure it was a lot of effort, and it would be great if someone could pick it up, but please warn potential users up front!

Perhaps @sckott or others at https://ropensci.org/ would be interested in taking it forward?

**Comment by sckott** [comment]
I do have access to WOS, but it's completely up to @crew102

**Comment by crew102** [comment]
@sckott , do you have access to the WoS APIs or just the WoS web app? You need a separate license/set of credentials for API use as compared to using the web app. I'd be happy to transition this package over to someone who can actually work on it moving forward. I lost access after I changed employers.

**Comment by sckott** [comment]
just explored whether I do have api access right now, says approval pending, so some higher up has to approve it, but sounds like I will.

**Comment by crew102** [comment]
k, let me know when you gain access and we can coordinate how to move forward

**Comment by sckott** [comment]
will do

**Comment by sckott** [comment]
@crew102 WOS wants to have a call with me before I get an API key. did you have to do that? Seems insance

**Comment by crew102** [comment]
How did you request access/credentials? Is there some organization that you work for that you're getting credentials through? Last I checked WoS API access is pretty expensive and only companies/schools end up subscribing. WoS probably wants to have a call with you to discuss how you'll be using their data.

**Comment by jslingsby** [comment]
Hmm... does seem a bit off-putting. I did some digging here and it seems my
institution (University of Cape Town) has a single API key and they're not
sharing. Users access WOS GUI and other resources with their institutional
(shibboleth) login, but that doesn't allow API authentication. I'd say the
value of the package is much reduced if institutional users can't call the
API...

**Comment by sckott** [comment]
access is through UC Berkeley. yes, i understand they want to know about how it will be used, but im annoyed by the barriers to getting an API key - theres many other academic search engines, with much less onerous API key registration. rant over.

**Comment by sckott** [comment]
@jslingsby i wonder how common that is? to not allow institutional users to have keys. if very common, not sure this is worth it

**Comment by jslingsby** [comment]
How did you apply for an API? I can have a go and see if I make the cut on
the interview ;)

**Comment by sckott** [comment]
Went to https://developer.clarivate.com/apis/wos -  create an account, then register an application, then I think I had to press a button to get an api key on that application, then it said "waiting for approval" or so, then got an email a bit later saying i had to do a call with them, haven't responded to the email yet

**Comment by jslingsby** [comment]
Perhaps a silly question, but should I register wosr as the application,
and if so, do you have the Application ID?

**Comment by sckott** [comment]
i don't think it matters what you call it

**Comment by crew102** [comment]
Yeah, so this must be a new process for getting a set of API credentials. Previously it was the case that you or your company/university had to have a separate contract with Clarivate (the people behind WoS) in order to get a set of credentials. I assume this new process is for some trial/limited-use use case. I just registered for an account so maybe they'll be trying to contact me too. And yes @sckott , there are other academic search engines that are both easier to register for and totally free, but WoS and Scopus are considered much better than most b/c of the good coverage they offer (in terms of which journals are indexed), as well as the quality of metadata (in terms of the actual fields they provide, the additional processing that's done on the fields such as disambiguation, the format that the data is served in, etc.).

**Comment by crew102** [comment]
Nevermind, looks like they still do require that you have a contract in place with your org in order to use the API...Assuming that means I won't be getting approved. 

![Screen Shot 2019-05-01 at 6 41 27 PM](https://user-images.githubusercontent.com/11220793/57048178-f5429900-6c40-11e9-9a70-33d52d2f1362.png)

**Comment by sckott** [comment]
had to have a call with a WOS person, decided I can't take this on, too cumbersome, and I think I'd only have access to the lite api

**Comment by crew102** [comment]
no problem, thanks anyway
